# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

require 'google/protobuf'

require './product_pb'


descriptor_data = "\n\x0border.proto\x12\tecommerce\x1a\rproduct.proto\"4\n\x0cOrderRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"L\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x13\n\x0btotal_price\x18\x03 \x01(\x02\x32P\n\x0cOrderService\x12@\n\x0b\x43reateOrder\x12\x17.ecommerce.OrderRequest\x1a\x18.ecommerce.OrderResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Ecommerce
  OrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ecommerce.OrderRequest").msgclass
  OrderResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ecommerce.OrderResponse").msgclass
end
