# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: order.proto for package 'ecommerce'
# Original file comments:
# order.proto

require 'grpc'
require './order_pb'

module Ecommerce
  module OrderService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ecommerce.OrderService'

      rpc :CreateOrder, ::Ecommerce::OrderRequest, ::Ecommerce::OrderResponse
    end

    Stub = Service.rpc_stub_class
  end
end
