# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

require 'google/protobuf'


descriptor_data = "\n\rproduct.proto\x12\tecommerce\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x32U\n\x0eProductService\x12\x43\n\nGetProduct\x12\x19.ecommerce.ProductRequest\x1a\x1a.ecommerce.ProductResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Ecommerce
  ProductRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ecommerce.ProductRequest").msgclass
  ProductResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ecommerce.ProductResponse").msgclass
end
