# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: product.proto for package 'ecommerce'
# Original file comments:
# product.proto

require 'grpc'
require 'product_pb'

module Ecommerce
  module ProductService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ecommerce.ProductService'

      rpc :GetProduct, ::Ecommerce::ProductRequest, ::Ecommerce::ProductResponse
    end

    Stub = Service.rpc_stub_class
  end
end
